decent_authentication-master/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'register' => 'users#new', as: 'register'
  get 'sign-in' => 'sessions#new', as: 'signin'
  delete 'sign-out' => 'sessions#destroy', as: 'signout'

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'profile' => 'profile#edit', as: 'profile'
  patch 'profile' => 'profile#update', as: 'update_profile'
end

decent_authentication-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

decent_authentication-master/app/models/user.rb
class User < ApplicationRecord

  validates :name, :email, presence: true
  validates_uniqueness_of :email, case_sensitive: false
  validates_format_of :email, with: /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i
  validates_length_of :password, minimum: 8, too_short: 'must be at least 8 characters', allow_nil: true
  validates_format_of :password, with: /\A(?=.*[a-z])(?=.*\d).+\z/i, message: 'must be alphanumeric', allow_nil: true

  before_save { |user| user.email.downcase! }

  has_secure_password
  has_secure_token :auth_token
  has_secure_token :password_reset_token

  def erase_password_reset_fields
    self.update(password_reset_token: nil, password_reset_sent_at: nil)
  end

end

decent_authentication-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :authenticated_user
  before_action :require_authentication
  add_flash_types :error, :success, :info, :warning

  private

  def authenticated_user
    @authenticated_user ||= User.find_by(auth_token: session[:auth_token]) if session[:auth_token]
  end

  def require_authentication
    unless authenticated_user
      session[:intended_destination] = params
      redirect_to signin_url, error: 'You must sign in to continue!'
    end
  end

end

decent_authentication-master/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_authentication
end

decent_authentication-master/app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_action :require_authentication

  def new
  end

  def create
    redirect_to new_password_reset_url, error: 'You must provide an email address!' and return if params[:email].blank?
    user = User.find_by(email: params[:email].downcase)
    SendPasswordResetRequest.new(user).call if user
    redirect_to signin_url, success: 'An email was just sent to you with password reset instructions.' and return
  end

  def edit
    @user = User.find_by(password_reset_token: params[:id])

    if @user.blank?
      redirect_to new_password_reset_url, error: 'Invalid request! Please use the form below to request password reset instructions again.' and return
    end
  end

  def update
    @user = User.find_by(password_reset_token: params[:id])
    password_recovery = RecoverPassword.new(@user, params).call

    if password_recovery.expired?
      redirect_to new_password_reset_url, error: password_recovery.flash
    elsif password_recovery.blank_password?
      render :edit
    elsif password_recovery.success?
      reset_session
      redirect_to signin_url, success: password_recovery.flash
    else
      render :edit
    end
  end

end

decent_authentication-master/app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def edit
    @user = authenticated_user
  end

  def update
    @user = authenticated_user
    if @user.update(user_params)
      redirect_to profile_url, success: 'Your profile was successfully updated!'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end

end

decent_authentication-master/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_authentication, only: [:new, :create]

  def new
    redirect_to root_url if authenticated_user
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    authentication_attempt = AuthenticateUser.new(user, params).call
    if authentication_attempt.success?
      intended_url = session[:intended_destination]
      reset_session
      session[:auth_token] = user.auth_token
      user.touch(:last_sign_in_at)
      flash[:success] = authentication_attempt.flash
      redirect_to intended_url.blank? ? root_url : intended_url
    else
      flash.now[:error] = authentication_attempt.flash
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to signin_url, success: 'You have successfully signed out!'
  end

end

decent_authentication-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_authentication, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.enabled = true
    if @user.save
      redirect_to signin_url, success: 'Thanks for signing up! You may now sign in.'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end

end

decent_authentication-master/app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    { success: 'alert-success', error: 'alert-danger', warning: 'alert-warning', info: 'alert-info' }[flash_type.to_sym] || flash_type.to_s
  end

  def model_error_display(model, attribute)
    if field_with_error?(model, attribute)
      content_tag(:small, "#{model.errors[attribute].first}", class: 'text-danger')
    end
  end

  def field_with_error?(model, attribute)
    model.errors[attribute].present?
  end

  def form_error_class(model, attribute)
    field_with_error?(model, attribute) ? 'is-invalid' : nil
  end

end

decent_authentication-master/app/views/application/_flash.html.haml
- flash.each do |type, message|
  %div(class="alert #{bootstrap_class_for(type)} alert-dismissible fade show" role="alert")
    %button.close{type: 'button', 'aria-label' => "Close", data: { dismiss: 'alert'}}
      %span(aria-hidden="true") &times;
    = message.html_safe if message

decent_authentication-master/app/views/home/index.html.haml
.container
  .row
    .col
      .jumbotron
        %h1.display-0 Welcome!
        %hr.my-2
        %p
  %link{:href => "https://www.w3schools.com/w3css/4/w3.css", :rel => "stylesheet"}/
  %link{:href => "https://www.w3schools.com/lib/w3-theme-black.css", :rel => "stylesheet"}/
  %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css", :rel => "stylesheet"}/
  .w3-row-padding.w3-center.w3-margin-top
    .w3-third
      .w3-card.w3-container{:style => "min-height:50px"}
        %h3 Configuration
        %br/
        %i.fa.fa-desktop.w3-margin-bottom.w3-text-theme{:style => "font-size:50px"}
    .w3-third
      .w3-card.w3-container{:style => "min-height:50px"}
        %h3 Alerts
        %br/
        %i.fa.fa-css3.w3-margin-bottom.w3-text-theme{:style => "font-size:50px"}
    .w3-third
      .w3-card.w3-container{:style => "min-height:50px"}
        %h3 MIS
        %br/
        %i.fa.fa-diamond.w3-margin-bottom.w3-text-theme{:style => "font-size:50px"}

decent_authentication-master/app/views/layouts/application.html.haml
!!!
%html{lang: 'en'}
  %head
    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no'}
    %title MIS
    = favicon_link_tag 'favicon.png', rel: 'shortcut icon', type: 'image/png'
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tag
  %body{class: "#{controller_name} #{action_name}"}
    - if authenticated_user
      %nav.navbar.navbar-expand-md.fixed-top.navbar-light.bg-light
        %ul.navbar-nav.mr-auto
          %li.nav-item
            = link_to root_path, class: 'nav-link' do
              <svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><title>decent authentication</title><path d="M32 19l-6-6v-9h-4v5l-6-6-16 16v1h4v10h10v-6h4v6h10v-10h4z"></path></svg>
              MIS
        %ul.navbar-nav.justity-content-right
          %li.nav-item
            = link_to profile_path, class: 'nav-link' do
              <svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><title>profile</title><path d="M18 22.082v-1.649c2.203-1.241 4-4.337 4-7.432 0-4.971 0-9-6-9s-6 4.029-6 9c0 3.096 1.797 6.191 4 7.432v1.649c-6.784 0.555-12 3.888-12 7.918h28c0-4.030-5.216-7.364-12-7.918z"></path></svg>
              Profile
          %li.nav-item
            = link_to signout_path, method: :delete, class: 'nav-link text-danger', id: 'nav-signout', data: { confirm: 'Are you sure you wish to sign out?' } do
              <svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><title>signout</title><path d="M24 20v-4h-10v-4h10v-4l6 6zM22 18v8h-10v6l-12-6v-26h22v10h-2v-8h-16l8 4v18h8v-6z"></path></svg>
              Sign out

    - unless flash.empty?
      .container
        = render partial: 'flash', locals: { flash: flash }
    = yield

    %footer.footer
      .container
        %span.text-muted Spice Digital
        %ul.list-inline.float-right.mb-0
          %li.list-inline-item.mr-3
            = link_to 'http://', target: '_blank' do
              <svg class="" xmlns="http://www.w3.org/2000/svg" viewBox=""><title></title></svg>
          %li.list-inline-item
            = link_to 'https://', target: '_blank' do
              <svg class="" xmlns="http://www.w3.org/2000/svg" viewBox=""><title></title></svg>

    = javascript_include_tag 'application'

decent_authentication-master/app/views/password_resets/edit.html.haml
.container
  .row.mt-5
    .col-lg-6.ml-auto.mr-auto
      .card
        %h4.card-header.text-center Change Password
        .card-body
          .alert.alert-info(role='alert')
            Passwords must be at least <strong>8 characters</strong> long and contain numbers and letters.
          = form_for @user, url: password_reset_path(params[:id]) do |f|
            .form-group{class: form_error_class(@user, :password)}
              %label(for='user_password') New Password
              = f.password_field :password, autofocus: true, required: true, class: 'form-control'
              = model_error_display(@user, :password)
            .form-group{class: form_error_class(@user, :password_confirmation)}
              %label(for='user_password_confirmation') Password Confirmation
              = f.password_field :password_confirmation, class: 'form-control'
              = model_error_display(@user, :password_confirmation)
            = f.submit 'Save', class: 'btn btn-block btn-primary', data: { disable_with: 'Please wait...' }

decent_authentication-master/app/views/password_resets/new.html.haml
.container
  .row.mt-5
    .col-lg-6.ml-auto.mr-auto
      .card
        %h4.card-header.text-center Reset Your Password
        .card-body
          = form_tag [:password_resets], method: :post do
            .form-group
              %label(for='email') Email
              = email_field_tag :email, params[:email], autofocus: true, class: 'form-control', required: true
            = submit_tag 'Send Instructions', class: 'btn btn-primary btn-block', data: { disable_with: 'Please wait...' }
      %p.text-center.my-3
        = link_to 'Sign In', signin_path

decent_authentication-master/app/views/users/new.html.haml
.container
  .row.mt-5
    .col-lg-6.ml-auto.mr-auto
      .card
        %h4.card-header.text-center Create Account
        .card-body
          = form_for @user do |f|
            - if @user.errors.any?
              .alert.alert-danger
                Please correct the errors below to continue.
            .form-group
              %label(for='user_name') Name
              = f.text_field :name, autofocus: true, class: "form-control #{form_error_class(@user, :name)}"
              = model_error_display(@user, :name)
            .form-group
              %label(for='user_email') Email
              = f.email_field :email, class: "form-control #{form_error_class(@user, :email)}"
              = model_error_display(@user, :email)
            .form-group
              %label(for='user_password') Password
              = f.password_field :password, class: "form-control #{form_error_class(@user, :password)}"
              = model_error_display(@user, :password)
            .form-group
              %label(for='user_password_confirmation') Password Confirmation
              = f.password_field :password_confirmation, class: "form-control #{form_error_class(@user, :password_confirmation)}"
              = model_error_display(@user, :password_confirmation)
            = f.submit 'Save', class: 'btn btn-block btn-primary'
      %p.text-center.my-3
        = link_to 'Sign In', signin_path